---
- name: install podman
  package:
    name: podman
    state: present
  when: ansible_distribution  != 'Debian'
  become: yes

- name: install cockpit-podman
  package:
    name: cockpit-podman
    state: present
  when: ansible_distribution  != 'Debian'
  become: yes

- name: deploy containers
  loop: "{{ PodmanContainers }}"
  import_tasks: "containers/{{ item }}/{{ item }}.yml"
  become_user: "{{ podman_user }}"