---
- name: "Add {{ item.name }} to fstab"
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: present
    line: "{{ item.src }} {{ item.mountpoint }} {{ item.type }} {{ item.opts }} 0 0" 
  register: mount_state

- name: "mount {{ item.name }}"
  command: mount "{{ item.mountpoint }}"
  when: mount_state.changed == true