---
- name: Add {{ item.name }} to fstab 
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: present
    line: "{{ item.src }} {{ item.mountpoint }} {{ item.type }} {{ item.opts }}" 
  mount_register: state

- name: mount {{ item.name }}
  command: mount "{{ item.mountpoint }}"
  when: state.changed == true