- name: Add servers to hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    line: "192.168.10.3 bigpuffer"

- name: make mount directorys
  loop: "{{ create_mounts }}"
  include_tasks: create_directorys.yml

- name: Add mounts to fstab and mount
  loop: "{{ create_mounts }}"
  include_tasks: fstab_mount.yml