- name: make mount directorys
  loop: "{{ create_mounts }}"
  include_tasks: create_directorys.yml

- name: Add mounts to fstab and mount them
  loop: "{{ create_mounts }}"
  include_tasks: fstab_mount.yml