---
- name: Playbook to configure bikinibodhi server
  hosts: 192.168.10.110
  become: true

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: bikinibodhi

    - name: Update linux
      ansible.builtin.include_role:
        name: update_linux

    - name: Disable SELinux
      ansible.builtin.include_tasks: "playbooks/selinux.yml"