---
- name: playbook to configure bigpuffer server
  hosts: 
    - bikinibodhi
    - raspberrypi
    #- bigpuffer
  vars_files:
    - vars/user.yml
    - vars/group.yml
  vars:
    ## mount vars
    create_mounts:
      - name: "Anime"
        mountpoint: "/media/Anime"
        type: "nfs"
        opts: "rw,sync,hard"
        src: "192.168.10.3:/Tank/Shares/Anime"
        state: present
      - name: "TV"
        mountpoint: "/media/TV"
        type: "nfs"
        opts: "rw,sync,hard"
        src: "192.168.10.3:/Tank/Shares/TV"
        state: present
    
    ## container vars
    ContainerData: /Containers
    PodmanContainers:
      #- Jellyfin
      #- Tdarr_Node
      #- Sonarr
      #- Heimdall
      - Lancache
      - Unbound
      #- Influxdb
    Anime: "/media/Anime"
    TV: "/media/TV"
    #Linuxserver.io vars
    UserID: 101009 # abc user
    GroupID: 101009 # serverio group
    TimeZone: Pacific/Auckland
    podman_user: abc
    ## Lancache 
    lancacheIP: 192.168.10.2
    
  tasks:
    # - name: update linux
    #   import_role:
    #     name: update_linux
    #   become: yes

    
    # - name: add mounts to fstab and mount it
    #   include_tasks: playbooks/mount/mount.yml

    # - name: add groups
    #   import_tasks: playbooks/create-group.yml    
    #   become: yes

    # - name: add users
    #   import_tasks: playbooks/create-user.yml
    #   become: yes

    # - name: install podman
    #   include_role: 
    #     name: podman_install
    - ansible.builtin.debug:
        msg: "{{ ansible_user  }}"
    - name: run containers
      import_role: 
        name: podman_containers
      become: yes
        