---
- name: Playbook to configure bigpuffer server
  hosts: bigpuffer
  become: true
  vars_files:
    - vars/containers.yml
    - vars/group.yml
    - vars/user.yml
    - vars/mounts.yml

  tasks:
    # - name: update linux
    #   include_tasks: playbooks/update-linux.yml

    - name: Add groups
      ansible.builtin.include_tasks: playbooks/create-group.yml

    - name: Add users
      ansible.builtin.include_tasks: playbooks/create-user.yml

#    - name: install and configure dnsmasq
#      include_tasks: playbooks/dnsmasq.yml

#    - name: install and enable samba
#      include_tasks: playbooks/samba.yml

#    - name: install and enable nfs server
#      include_tasks: playbooks/nfs-server.yml

#    - name: install and enable glusterfs
#      include_tasks: playbooks/glusterfs.yml

#    - name: add mounts to fstab and mount it
#      include_tasks: playbooks/mount/mount.yml

    - name: Install and enable cockpit
      ansible.builtin.include_tasks: playbooks/cockpit.yml
#    - name: install and enable nebula
#      include_tasks: playbooks/nebula.yml

    # - name: install and load openzfs
      # include_tasks: playbooks/open-zfs-install.yml

    - name: Add cockpit zfs manager
      ansible.builtin.include_tasks: playbooks/cockpit-zfs-manager.yml

    # - name: Run containers
      # ansible.builtin.include_tasks: containers/Containers_main.yml
