---
- name: playbook to configure bigpuffer server
  hosts: all
  become: yes
  vars_files:
    - vars/containers.yml
    - vars/group.yml
    - vars/user.yml
    - vars/mounts.yml

  tasks:
    - name: update linux
      include: playbooks/update-linux.yml

    - name: add groups
      include: playbooks/create-group.yml

    - name: add users
      include: playbooks/create-user.yml
  
    #- name: disable systemd-resolved
    #  include: playbooks/systemd-resolved.yml
    
    #- name: install and configure dnsmasq
     # include: playbooks/dnsmasq.yml
    
    - name: config fstab
      include: playbooks/fstab.yml

    - name: install and enable cockpit
      include: playbooks/cockpit.yml

    #- name: install and enable samba
    #  include: playbooks/samba.yml

    #- name: install and enable nfs server
    #  include: playbooks/nfs-server.yml

    - name: install and load openzfs
      include: playbooks/open-zfs-install.yml

    - name: add cockpit zfs manager
      include: playbooks/cockpit-zfs-manager.yml

    #- name: install podman
    #  include: playbooks/podman.yml

    - name: run containers
      include: containers/main.yml
