---
- name: playbook to configure bigpuffer server
  hosts: 
    - bigpuffer
  become: yes

  tasks:
    - name: update linux
      include_tasks: playbooks/update-linux.yml 
    
    - include_tasks: playbooks/sanoid/sanoid.yml