---
- name: Playbook to update all servers
  hosts:
    # - 192.168.10.1
    # - 192.168.10.53
    - bigpuffer
    # - hpelite
    # - gateway
    # - ubuntu-us-central
  become: true

  tasks:
    - name: Update linux
      ansible.builtin.include_role:
        name: update_linux

    - name: Install Unattended Upgrades
      ansible.builtin.include_tasks: playbooks/automated-updates/unattended_upgrades.yml
      when: ansible_distribution == 'Debian'
