---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: lscr.io/linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    generate_systemd:
      new: false
      names: true
      path: /etc/systemd/system/
      restart_policy: "on-failure"
    env:
      PUID="{{ user_id }}"
      PGID="{{ group_id }}"
      TZ="{{ time_zone }}"
      URL="shedinternet.net"
      SUBDOMAINS="cloud,wwww"
      VALIDATION="dns"
      DNSPLUGIN="cloudflare"
    volume:
      - "{{ container_data }}/{{ item }}/Config:/config:rw"
    ports:
      - "443:443"

- name: Make sure {{ item }} service is enabled and started
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"