---
- name: "install debhelper libcapture-tiny-perl libconfig-inifiles-perl pv lzop mbuffer build-essential git"
  package:
    name:
      - debhelper
      - libcapture-tiny-perl
      - libconfig-inifiles-perl
      - pv
      - lzop
      - mbuffer
      - build-essential
      - git
    state: present

- name: git clone sanoid
  ansible.builtin.git:
    repo: https://github.com/jimsalterjrs/sanoid.git
    dest: /tmp/sanoid

- name: copy sanoid files
  copy:
    src: /tmp/sanoid/{{ item }} 
    dest: /usr/local/sbin
    remote_src: yes
  loop: 
    - sanoid
    - syncoid
    - findoid
    - sleepymutex