---
- name: "install debhelper libcapture-tiny-perl libconfig-inifiles-perl pv lzop mbuffer build-essential git Debian"
  package:
    name:
      - debhelper
      - libcapture-tiny-perl
      - libconfig-inifiles-perl
      - pv
      - lzop
      - mbuffer
      - build-essential
      - git
    state: present

