---
- name: "install epel-release, git and dnf-plugins-core"
  package:
    name:
      - epel-release
      - git
      - dnf-plugins-core
    state: present

- name: add powertools
  dnf:
    enablerepo: powertools
    state: present

- name: git clone sanoid
  ansible.builtin.git:
    repo: https://github.com/jimsalterjrs/sanoid.git
    dest: /tmp/sanoid

- name: copy sanoid files
  copy:
    src: /tmp/sanoid/{{ item }} 
    dest: /usr/local/sbin
    remote_src: yes
  loop: 
    - sanoid
    - syncoid
    - findoid
    - sleepymutex