---
- name: "install epel-release, git and dnf-plugins-core Redhat"
  package:
    name:
      - epel-release
      - git
      - dnf-plugins-core
    state: present

- name: "install perl, mbuffer and pv Redhat"
  package:
    name:
      - perl-Config-IniFiles
      - perl-Data-Dumper
      - perl-Capture-Tiny 
      - lzop 
      - mbuffer
      - mhash
      - pv
    state: present

- name: add powertools Redhat
  dnf:
    enablerepo: powertools
    state: present