---
- name: Install sanoid for Redhat
  include_tasks: install_Redhat.yml
  when: ansible_distribution  == 'Redhat'

- name: Install sanoid for Debian
  include_tasks: install_Debian.yml
  when: ansible_distribution  == 'Debian'

- name: git clone sanoid 
  ansible.builtin.git:
    repo: https://github.com/jimsalterjrs/sanoid.git
    dest: /tmp/sanoid

- name: copy sanoid files
  copy:
    src: /tmp/sanoid/{{ item }} 
    dest: /usr/local/sbin
    remote_src: yes
  loop: 
    - sanoid
    - syncoid
    - findoid
    - sleepymutex

- name: Create /etc/sanoid
  file:
    path: /etc/sanoid
    state: directory
   
- name: copy sanoid.conf file
  copy:
    src: files/sanoid/sanoid.conf
    dest: /etc/sanoid/sanoid.conf

- name: copy sanoid systemd files
  loop:
    - sanoid.service
    - sanoid-prune.service
    - sanoid.timer
  copy:
    src: files/sanoid/{{ item }}
    dest: /etc/systemd/system

- name: enable and start sanoid-prune
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    name: sanoid-prune
    
- name: enable and start sanoid.timer
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: sanoid.timer