---
- name: Create {{ item }} config folder
  file:
    path: "/Container/{{ item }}/config"
    state: directory

- name: Create {{ item }} logs folder
  file:
    path: "/Container/{{ item }}/logs"
    state: directory

- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: ghcr.io/linuxserver/jellyfin:latest
    state: created
    ports:
      - 8096:8096
    volume:
      - "{{ ContainerLogs }}/{{ item }}:/config/log:rw"
      - "{{ ContainerConfigs }}/{{ item }}:/config:rw"
    env:
      PUID="{{ UserID }}"
      PGID="{{ GroupID }}"
      TZ="{{ TimeZone }}"
  register: state

- name: Make {{ item }} Systemd service
  shell: cd /etc/systemd/system/ && podman generate systemd --files --name {{ item }}
  when: state.changed == true

- name: restart {{ item }} service if change
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == true

- name: Start {{ item }} service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == false

- name: allow 8096/tcp on firewalld
  ansible.posix.firewalld:
    port: 8096/tcp
    permanent: yes
    state: enabled