---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image:  docker.io/library/telegraf:latest
    generate_systemd:
      new: false
      names: true
      path: /etc/systemd/system/
      restart_policy: "on-failure"
    env:
      - HOST_ETC="/hostfs/etc"
      - HOST_PROC="/hostfs/proc"
      - HOST_SYS="/hostfs/sys"
      - HOST_var="/hostfs/var"
      - HOST_RUN="/hostfs/run"
      - HOST_MOUNT_PREFIX="/hostfs"
    volume:
      - "{{ ContainerData }}/{{ item }}/Config/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/:/hostfs:ro"