---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: ghcr.io/linuxserver/qbittorrent
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8088:8088
    env:
      WEBUI_PORT=8088
      PUID="{{ user_id }}"
      PGID="{{ group_id }}"
      TZ="{{ time_zone }}"
    volume:
      - "{{ container_data }}/{{ item }}/config:/config:Z,rw" # private to this container
      - "{{ container_data }}/Sonarr:/downloads:z,rw" # shared for other containers
  register: state

#podman generate systemd --files --name Wordpress 
#Auto Generate systemd files
# cd ~/.config/systemd/user && /usr/bin/podman generate systemd --files --name {{ item }}
- name: Make {{ item }} Systemd service
  shell: cd /etc/systemd/system && podman generate systemd --files --name {{ item }}
  when: state.changed == true

- name: restart {{ item }} service if change
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == true

- name: Start {{ item }} service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == false