---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: ghcr.io/linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    ports:
      - 9443:443
    security_opt:
      label=type:Letsencrypt.process
    env:
      PUID="{{ UserID }}"
      PGID="{{ GroupID }}"
      TZ="{{ TimeZone }}"
      URL="shedinternet.net"
      SUBDOMAINS="www,cloud,tv,git,code-server"
      VALIDATION="dns"
      DNSPLUGIN="cloudflare"
    volume:
      - "/Container/{{ item }}/config:/config:Z,rw"
  register: state

- name: Make {{ item }} Systemd service
  shell: cd /etc/systemd/system/ && podman generate systemd --files --name {{ item }}
  when: state.changed == true

- name: restart {{ item }} service if change
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == true

- name: Start {{ item }} service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == false
