---
- name: Add testing repositorys for Debian 10
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    state: present
    line: deb http://http.us.debian.org/debian/ testing non-free contrib main
  when: ansible_distribution  == 'Debian'

- name: install podman | Debian
  apt:
    name: podman
    update_cache: yes
    state: present
  when: ansible_distribution  == 'Debian'

- name: install podman
  package:
    name: podman
    state: present
  when: ansible_distribution  != 'Debian'

- name: deploy containers
  loop: "{{ PodmanContainers }}"
  include_tasks: "containers/{{ item }}/{{ item }}.yml"
