---
- name: Pull an image {{ item }}
  containers.podman.podman_image:
    name: ghcr.io/linuxserver/transmission:latest

- name: Make "{{ item }}" Systemd service
  copy:
    dest: "/etc/systemd/system/container-{{ item }}.service"
    content: |
      [Unit]
      Description={{ item }} container
      After=multi-user.target
      Wants=multi-user.target, network-online.target
      RequiresMountsFor={{ container_data }}/{{ item }}, /run/containers/storage


      [Service]
      TimeoutStartSec=0
      ExecStartPre=-/usr/bin/podman kill {{ item }}
      ExecStartPre=-/usr/bin/podman rm {{ item }}
      ExecStartPre=-/usr/bin/podman pull ghcr.io/linuxserver/transmission:latest
      ExecStart=/usr/bin/podman run \
      --name {{ item }} \
      -e PUID="{{ user_id }}" \
      -e PGID="{{ group_id }}" \
      -e TZ="{{ time_zone }}" \
      -e USER="{{ sonarr_user }}" \
      -e PASS="{{ sonarr_password }}" \
      -v "{{ container_data }}/{{ item }}/Config:/config:rw" \
      -v "{{ container_data }}/{{ item }}/Downloads:/downloads:rw" \
      -v "{{ container_data }}/{{ item }}/Watch:/watch:rw" \
      -p 9091:9091 \
      -p 51413:51413 \
      -p 51413:51413/udp \
      ghcr.io/linuxserver/transmission:latest

      ExecStop=/usr/bin/podman stop {{ item }}

      [Install]
      WantedBy=multi-user.target
  register: state

- name: Pause for 10 seconds to start app
  pause:
    seconds: 10
  when: state.changed == true


- name: restart {{ item }} service if change
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == true

- name: Start {{ item }} service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == false
