---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: docker.io/klutchell/unbound
    generate_systemd:
      new: false
      names: true
      path: "/etc/systemd/system/"
      restart_policy: "on-failure"
    ports:
      - 5335:53/tcp
      - 5335:53/udp
    volume:
      - "{{ container_data }}/{{ item }}/Config:/etc/unbound:rw"


- name: Start {{ item }} service
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"
