---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: docker.io/klutchell/unbound
    generate_systemd:
      new: false
      names: true
      path: "/etc/systemd/system/"
      restart_policy: "on-failure"
    ports:
      - 5335:53/tcp
      - 5335:53/udp
    volume:
      - "{{ ContainerData }}/{{ item }}/Config:/etc/unbound:rw"
  register: state

# - name: Make {{ item }} Systemd service
#   shell: cd /etc/systemd/system/ && podman generate systemd --files --name {{ item }}
#   when: state.changed == true

- name: restart {{ item }} service if change
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    scope: user
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == true

- name: Start {{ item }} service
  ansible.builtin.systemd:
    state: started
    scope: user
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == false