---
# tasks file for podman_containers
- name: Install podman
  ansible.builtin.package:
    name: podman
    state: present

# - name: install cockpit-podman
#   package:
#     name: cockpit-podman
#     state: present
#   when: ansible_distribution  != 'Debian'

- name: Deploy containers
  loop: "{{ podman_containers }}"
  ansible.builtin.include_tasks: "containers/{{ item }}/{{ item }}.yml"
