---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: docker.io/adguard/adguardhome:latest
    state: started
    generate_systemd:
      new: false
      names: true
      path: /etc/systemd/system/
      restart_policy: "on-failure"
    volume:
      - "{{ container_data }}/{{ item }}/Config:/opt/adguardhome/conf:rw"
      - "{{ container_data }}/{{ item }}/Work:/opt/adguardhome/work:rw"      
    ports:
      - "192.168.10.3:80:80"
      - "192.168.10.3:53:53/tcp"
      - "192.168.10.3:53:53/udp"
      - "192.168.10.3:443:443/tcp"
      - "192.168.10.3:443:443/udp"
      - "192.168.10.3:3080:3000/tcp"              

- name: Make sure {{ item }} service is enabled and started
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"