---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: lscr.io/linuxserver/jellyfin:latest
    generate_systemd:
      new: false
      names: true
      path: /etc/systemd/system/
      restart_policy: "on-failure"
    env:
      PUID="{{ UserID }}"
      PGID="{{ GroupID }}"
      TZ="{{ TimeZone }}"
    volume:
      - "{{ ContainerData }}/{{ item }}/Config:/config:rw"
      - "{{ Anime }}:/Anime:rw" 
      - "{{ TV }}:/TV:rw" 
      - "{{ Youtube }}:/Youtube:rw"
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      # - "1900:1900/udp"