---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: lscr.io/linuxserver/jellyfin:latest
    generate_systemd:
      new: false
      names: true
      path: /etc/systemd/system/
      restart_policy: "on-failure"
    # device:
    #   - /dev/dri:/dev/dri
    env:
      PUID="{{ user_id }}"
      PGID="{{ group_id }}"
      TZ="{{ time_zone }}"
    volume:
      - "{{ container_data }}/{{ item }}/Config:/config:rw"
      - "{{ anime }}:/Anime:rw"
      - "{{ tv }}:/TV:rw"
      - "{{ youtube }}:/Youtube:rw"
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      # - "1900:1900/udp"
    
- name: start and enable {{ item }} 
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"