---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: lscr.io/linuxserver/heimdall:latest
    generate_systemd:
      new: false
      names: true
      path: "/etc/systemd/system/"
      restart_policy: "on-failure"
    ports:
      - 4443:443
    env:
      PUID="{{ UserID }}"
      PGID=""{{ GroupID }}""
      TZ="{{ TimeZone }}"
    volume:
      - "{{ ContainerData }}/{{ item }}/Config:/config:rw"