---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: ghcr.io/linuxserver/qbittorrent
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8088:8088
    env:
      WEBUI_PORT=8088
      PUID="{{ UserID }}"
      PGID="{{ UserID }}"
      TZ="{{ TimeZone }}"
    volume:
      - "{{ ContainerConfigs }}/{{ item }}:/config:rw"
      - "{{ ContainerCache }}/Sonarr:/downloads:z,rw"
  register: state

#podman generate systemd --files --name Wordpress 
#Auto Generate systemd files
# cd ~/.config/systemd/user && /usr/bin/podman generate systemd --files --name {{ item }}
- name: Make {{ item }} Systemd service
  shell: cd /etc/systemd/system && podman generate systemd --files --name {{ item }}
  when: state.changed == true

- name: restart {{ item }} service if change
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == true

- name: Start {{ item }} service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == false

- name: allow 8088/tcp on firewalld
  ansible.posix.firewalld:
    port: 8088/tcp
    permanent: yes
    state: enabled

- name: allow 6881/udp on firewalld
  ansible.posix.firewalld:
    port: 6881/udp
    permanent: yes
    state: enabled

- name: allow 51413/tcp on firewalld
  ansible.posix.firewalld:
    port: 6881/tcp
    permanent: yes
    state: enabled