---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: ghcr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    env:
      PUID="{{ UserID }}"
      PGID="{{ UserID }}"
      TZ="{{ TimeZone }}"
      USER="{{ Sonarr_User }}"
      PASS="{{ Sonarr_Password }}"
    volume:
      - "{{ ContainerConfigs }}/{{ item }}:/config:rw" # locks to only this container
      - "{{ ContainerCache }}/{{ item }}:/downloads:rw" # Share with any Container
      - "{{ Anime }}:/anime:rw"
  register: state

- name: Make {{ item }} Systemd service
  shell: cd /etc/systemd/system/ && podman generate systemd --files --name {{ item }}
  when: state.changed == true

- name: restart {{ item }} service if change
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == true

- name: Start {{ item }} service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == false

- name: allow 8989/tcp on firewalld
  ansible.posix.firewalld:
    port: 8989/tcp
    permanent: yes
    state: enabled