---
- name: Create {{ item }} pod
  containers.podman.podman_pod:
    name: "{{ item }}"
    state: started
    ports:
      - "8989:8989"
      - "9091:9091"
      - "9117:9117"
    generate_systemd:
      new: false
      names: true
      path: /etc/systemd/system/
      restart_policy: "on-failure"

- name: Create {{ item }}_Jackett Podman Container
  containers.podman.podman_container:
    name: "{{ item }}_Jackett"
    pod: "{{ item }}"
    generate_systemd:
      new: false
      names: true
      path: /etc/systemd/system/
      restart_policy: "on-failure"
    image: lscr.io/linuxserver/jackett:latest
    env:
      PUID="{{ UserID }}"
      PGID="{{ GroupID }}"
      TZ="{{ TimeZone }}"
    volume:
      - "{{ ContainerData }}/Jackett/Config:/config:rw"
      - "{{ ContainerData }}/Jackett/Downloads:/downloads:rw"


- name: Create {{ item }}_Transmission Podman Container
  containers.podman.podman_container:
    name: "{{ item }}_Transmission"
    pod: "{{ item }}"
    generate_systemd:
      new: false
      names: true
      path: /etc/systemd/system/
      restart_policy: "on-failure"
    image: lscr.io/linuxserver/transmission:latest
    env:
      PUID="{{ UserID }}"
      PGID="{{ GroupID }}"
      TZ="{{ TimeZone }}"
    volume:
      - "{{ ContainerData }}/Transmission/Config:/config:rw"
      - "{{ ContainerData }}/Transmission/Downloads:/downloads:rw"
      - "{{ ContainerData }}/Transmission/Watch:/watch:rw" 

- name: Create {{ item }}_app Podman Container
  containers.podman.podman_container:
    name: "{{ item }}_app"
    pod: "{{ item }}"
    image: lscr.io/linuxserver/sonarr:latest
    generate_systemd:
      new: false
      names: true
      path: /etc/systemd/system/
      restart_policy: "on-failure"
    requires: 
      - "{{ item }}_Jackett"
      - "{{ item }}_Transmission"
    env:
      PUID="{{ UserID }}"
      PGID="{{ GroupID }}"
      TZ="{{ TimeZone }}"
    volume:
      - "{{ ContainerData }}/{{ item }}/Config:/config:rw"
      - "{{ ContainerData }}/Transmission/Downloads:/downloads:rw"
      - "{{ Anime }}:/Anime:rw" 
      - "{{ TV }}:/TV:rw" 
      - "{{ Youtube }}:/Youtube:rw"