---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image:  lscr.io/linuxserver/plex:latest
    generate_systemd:
      new: false
      names: true
      path: /etc/systemd/system/
      restart_policy: "on-failure"
    env:
      PUID="{{ user_id }}"
      PGID="{{ group_id }}"
      TZ="{{ time_zone }}"
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volume:
      - "{{ container_data }}/{{ item }}/Config:/config:rw"
      - "{{ anime }}:/Anime:rw" 