---
# tasks file for update_linux
## Makes sure python3 and pip3 are installed
- name: Install python3 and pip3
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present

## Updates all local packages
- name: Update all current packages
  ansible.builtin.package:
    name: "*"
    state: latest
