---

- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: docker.io/jasonrivers/nagios:latest
    state: present
    generate_systemd:
      new: false
      names: true
      path: /etc/systemd/system/
      restart_policy: "on-failure"
    ports:
      - "9443:443"
    env:
      PUID="{{ user_id }}"
      PGID="{{ group_id }}"
      TZ="{{ time_zone }}"
    volume:
      - "{{ container_data }}/{{ item }}/etc:/opt/nagios/etc:rw"
      - "{{ container_data }}/{{ item }}/var:/opt/nagios/var:rw"
      - "{{ container_data }}/{{ item }}/Custom-Nagios-Plugins:/opt/Custom-Nagios-Plugins:rw"
      - "{{ container_data }}/{{ item }}/nagiosgraph/var:/opt/nagiosgraph/var:rw"
      - "{{ container_data }}/{{ item }}/nagiosgraph/etc:/opt/nagiosgraph/etc:rw"

- name: Start {{ item }} service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"
