---
- name: Install cockpit
  ansible.builtin.package:
    name: cockpit
    state: present

- name: Enable and start cockpit.socket
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: cockpit.socket

- name: Allow cockpit on firewalld
  ansible.posix.firewalld:
    service: cockpit
    permanent: yes
    state: enabled
  when: ansible_distribution  == 'Redhat'