---
- name: Create standard User
  loop: "{{ create_users }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: /bin/bash
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }}"
  when: item.type is not defined

- name: Create Admin RedHat User
  loop: "{{ create_users }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: /bin/bash
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }},wheel"
  when: item.type is defined and item.type == "admin" and ansible_os_family == "RedHat"

- name: Create Admin Debian User
  loop: "{{ create_users }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: /bin/bash
    uid: "{{ item.uid }}"
    groups: "{{ item.groups }},sudo"
  when: item.type is defined and item.type == "admin" and ansible_os_family == "Debian"
