---
- name: install dnsmasq
  package:
    name: dnsmasq
    state: present

- name: Copy dnsmasq config file
  ansible.builtin.copy:
    src: files/dnsmasq/dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: dnsmasq
    mode: '0644'

  
- name: start and enable dnsmasq
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: dnsmasq