- name: make directorys for "{{ item }}"
  loop: "{{ create_mounts }}"
  file:
    path: "{{ item.mountpoint }}"
    state: directory

- name: Mount {{ item }}
  loop: "{{ create_mounts }}"
  ansible.posix.mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.src }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.opts }}"
    state: mounted