- name: make directorys for {{ item }}
  loop: "{{ create_mounts }}"
  file:
    path: "{{ mountpoint }}"
    state: directory

- name: Mount {{ item }}
  loop: "{{ create_mounts }}"
  ansible.posix.mount:
    path: "{{ mountpoint }}"
    src: "{{ src }}"
    fstype: "{{ type }}"
    opts: "{{ opts }}"
    state: mounted