- name: make mount directorys
  loop: "{{ create_mounts }}"
  file:
    path: "{{ item.mountpoint }}"
    state: directory

- name: Add mounts to fstab
  loop: "{{ create_mounts }}"
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: present
    line: "{{ item.src }} {{ item.mountpoint }} {{ item.type }} {{ item.opts }}" 

- name: mount
  loop: "{{ create_mounts }}"
  ansible.posix.mount:
    path: "{{ item.mountpoint }}"
    state: remounted