- name: make directorys for "{{ item }}"
  loop: "{{ create_mounts }}"
  file:
    path: "{{ item.mountpoint }}"
    state: directory

- name: Add "{{ item.name }}" to fstab
  loop: "{{ create_mounts }}"
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: present
    regexp: "{{ item.src }} {{ item.mountpoint }} {{ item.type }} {{ item.opts }}" 