---
- name: install nfs server Redhat
  package:
    name: nfs-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: install nfs server Debian
  package:
    name: nfs-common
    state: present
  when: ansible_os_family == "Debian"

- name: start and enable nfs-server
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: nfs-server